### ISSUE TITLE
Pre-processing

### ISSUE THREAD

**Issue by abhinav-iiit** [seva100/optic-nerve-cnn#1]
Can somebody please clearly state the preprocessing(cropping, resizing, CLAHE) steps taken ? I am not able to follow up.  I understand the image augmentation techniques (random flips, rotations etc) deployed using generator.

**Comment by seva100** [comment]
@abhinav-iiit, in the presented version of notebooks, at the preprocessing stage all images are rescaled to [0, 1], resized to 256x256, and CLAHE is applied.

**Comment by abhinav-iiit** [comment]
Thanks!
Let me know if the following is correct for optic cup :
1) Area of size 512x512 centered around optic disc is cropped from original image.
2) Rescaled to [0,1], resized to 256x256, CLAHE applied
3) Again resized to 128x128

**Comment by seva100** [comment]
@abhinav-iiit, not exactly, the order used is:
1. Area of size 512x512 centered around optic disc is cropped from an original image.
2. Resized to 128x128.
3. Rescaled to [0, 1], CLAHE applied.

Besides, augmentation is applied before CLAHE for both tasks (see `preprocess(...)`).

**Comment by seva100** [comment]
You will probably find the [original article](https://arxiv.org/pdf/1704.00979.pdf) helpful, which explains the algorithm in plain English.
