### ISSUE TITLE
Unable to replicate 

### ISSUE THREAD

**Issue by abhinav-iiit** [seva100/optic-nerve-cnn#2]
Dear Artem,
Can you please review my code https://github.com/abhinav-iiit/fundus-image-segmentation . I am unable to reproduce the results despite using weights mentioned here - https://github.com/seva100/optic-nerve-cnn/tree/master/models_weights

**Comment by seva100** [comment]
@abhinav-iiit, I see that you have rewritten the code fully, so the divergence in quality can be for virtually any reason. I have to ask you to find the reason behind it by yourself, as it is technically not an issue with this repository.
Anyway, what I have noticed is that your output images look very strange: https://github.com/abhinav-iiit/fundus-image-segmentation/blob/master/output/output_1.png. Probably this is one of the reasons.

**Comment by abhinav-iiit** [comment]
@seva100 Output images look very strange and that is precisely the problem! Despite using the weights arrived upon by you, I am unable to produce the results.
