### ISSUE TITLE
Hdf5

### ISSUE THREAD

**Issue by Sayantan17** [seva100/optic-nerve-cnn#5]
@seva100 Can u tell how to create .h5py file? From random.sets of fundus images probably(DRISHTI/DRIONS) for getting them to 
h5py file thought the code u mentioned in scrips ? How can I be able to import the images  & their CSV format file. I just want to create a new h5py file supposingly so can I be able to do that. I think that the one u provided in script is taking data from preexisting h5py file .

**Comment by seva100** [comment]
@Sayantan17 you can follow the `scripts/Organize datasets.ipynb` notebook, it contains the code which was used to create h5py files for all datasets that were used for the algorithm evaluation. 
To create simplest h5py file, you can use smth like

```python
import h5py
h5f = h5py.File("your_h5py_file.h5", "w")
h5f['images'] = images_ar    # images_ar -- numpy array of shape (n_images, n_channels, H, W)
h5f.close()
```
For further examples please follow the [h5py documentation](http://docs.h5py.org/en/latest/).

**Comment by Sayantan17** [comment]
Hey @seva100 Sir can I have your email so.that I can  email my problems directly so that I can directly contact you , as I am working in a research paper on this topic as I think email is better means of communication.
