### ISSUE TITLE
Problem in Hdf5 creation

### ISSUE THREAD

**Issue by Sayantan17** [seva100/optic-nerve-cnn#6]
@seva100 , sorry to disturb again, can you help me with the code to create an hdf5 file creation of a folder containing approximately 8k (6k training & 1k training & 1k for testing) , location in a directory let's say D:/New Folder/(8k images) , which are of different sizes(pixel values).I am getting confused.
Immediate help would be appreciated.
Thanks.

**Comment by seva100** [comment]
@Sayantan17, you should use open each file with e.g. `imageio.imread`, resize it with e.g. `skimage.transform.resize` and save to an hdf5 file. 
If you have any specific question with programming, resources like [StackOverflow](stackoverflow.com) are better suited for that, as I believe.
